server:
  port: ${port:8080}
  servlet:
    context-path: ${context-path:/}

spring:
  profiles:
    active: dev #默认为开发环境
  datasource:
    driver-class-name: ${jdbc_driver:com.mysql.jdbc.Driver}
    url: ${jdbc_url:jdbc:mysql://db:3306/openmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    username: ${jdbc_user:mall}
    password: ${jdbc_password:mall123}
    dbType: ${db_type:mysql}
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: ${mongo-host:mongo}
      port: ${mongo-port:27017}
      database: ${mongo-db:mall-port}

  redis:
    host: ${redis-host:redis}  # Redis服务器地址
    database: ${redis-db:0} # Redis数据库索引（默认为0）
    port: ${redis-port:6379} # Redis服务器连接端口
    password: ${redis-password:}# Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

  liquibase:
    enabled: false

  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

liquibase:
  modules: mall/base,mall/cms,mall/oms,mall/pms,mall/sms,mall/ums,mall/sys

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    global-config:
      db-config:
        column-underline: true
        db-type: mysql
        field-strategy: not_empty
        id-type: id_worker
        logic-delete-value: 0
        logic-not-delete-value: 1
      refresh: true
  mapper-locations:
    - classpath*:dao/*.xml
    - classpath*:org/openmall/**/mapper/*.xml

# 自定义redis key
redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /sys/user/login
      - /sys/user/register
      - /sys/user/info
      - /sys/user/logout
      - /minio/upload

aliyun:
  oss:
    endpoint: ${aliyun-endpint:oss-cn-shanghai.aliyuncs.com} # oss对外服务的访问域名
    accessKeyId: ${aliyun-key:LTAI4FpAjqBbELwve5hAzoKZ} # 访问身份验证中用到用户标识
    accessKeySecret: ${aliyun-secret:r6MlcyzVgtQhSBiNDFIqpLOMr4QqdB} # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: ${aliyun-bucket:emall-oss} # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: ${aliyun-callback:/mall-admin/aliyun/oss/callback} # 文件上传成功后的回调地址
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀

minio:
  endpoint: http://192.168.3.101:9090 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    org.openmall.mall: debug
#  file: demo_log.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称
