server:
  port: ${port:8083}
  servlet:
    context-path: ${context-path:/}

spring:
  profiles:
    active: dev #默认为开发环境

  datasource:
    driver-class-name: ${jdbc_driver:com.mysql.jdbc.Driver}
    url: ${jdbc_url:jdbc:mysql://db:3306/openmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    username: ${jdbc_user:mall}
    password: ${jdbc_password:mall123}
    dbType: ${db_type:mysql}
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: ${es_nodes:es:9300}

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    global-config:
      db-config:
        column-underline: true
        db-type: mysql
        field-strategy: not_empty
        id-type: id_worker
        logic-delete-value: 0
        logic-not-delete-value: 1
      refresh: true
  mapper-locations:
    - classpath*:dao/*.xml
    - classpath*:org/openmall/**/mapper/*.xml
  typeAliasesPackage: org.openmall.mall.pms.domain

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4FpAjqBbELwve5hAzoKZ # 访问身份验证中用到用户标识
    accessKeySecret: r6MlcyzVgtQhSBiNDFIqpLOMr4QqdB # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: emall-oss # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: ${aliyun-callback:/mall-admin/aliyun/oss/callback} # 文件上传成功后的回调地址
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀

logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    org.openmall.mall: debug
#  file: demo_log.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称



