server:
  port: ${port:8081}
  servlet:
    context-path: ${context-path:/}

spring:
  profiles:
    active: dev #默认为开发环境

  datasource:
    driver-class-name: ${jdbc_driver:com.mysql.jdbc.Driver}
    url: ${jdbc_url:jdbc:mysql://db:3306/openmall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    username: ${jdbc_user:mall}
    password: ${jdbc_password:mall123}
    dbType: ${db_type:mysql}
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

mybatis:
  mapper-locations:
    - classpath*:dao/*.xml
    - classpath*:org/openmall/**/mapper/*.xml

logging:
  level:
    root: info
    org.openmall.mall: debug



