version: '3'

services:
  mall-admin:
    image: szopen/mall-admin:1.1-SNAPSHOT
    container_name: demo-mall-admin
    environment:
      - spring.profiles.active=demo
      - port=8080
    ports:
      - 8180:8080
    external_links:
      - mall-mysql:db
      - mall-redis:redis
  mall-portal:
    image: szopen/mall-portal:1.1-SNAPSHOT
    container_name: demo-mall-portal
    environment:
      - spring.profiles.active=demo
      - port=8080
    ports:
      - 8185:8080
    external_links:
      - mall-mysql:db
      - mall-redis:redis
      - mall-mongo:mongo
      - mall-rabbitmq:rabbit
